apiVersion: v1
kind: Service
metadata:
  name: guestbook-ulysse
  labels:
    app: guestbook-ulysse
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: guestbook-ulysse
