name: 'Push images'
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}


      - name: Build Docker image
        run: docker build . --file Dockerfile --tag dobyulysse/guestbook:$GITHUB_SHA
        working-directory: ./guestbook

      - name: Push Docker image
        run: docker push dobyulysse/guestbook:$GITHUB_SHA

      - name: Google auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud container clusters get-credentials cluster-1 --zone europe-west1-b --project kubernetes-187222'
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        
      - name: Deploy the application
        run: kubectl create deployment guestbook-ulysse --image=UlysseDoby/guestbook:$GITHUB_SHA
        continue-on-error: true

      - name: Deploy application
        run: kubectl set image deployment/guestbook-ulysse guestbook=UlysseDoby/guestbook:$GITHUB_SHA

      - name: apply all K8S YAML
        run: kubectl apply -f ./deploy
